source 'https://rubygems.org'

gem "paperclip", "~> 4.2"
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
    gem 'byebug'
    gem 'capybara', '~> 2.4.1'
    gem 'poltergeist', '~> 1.5.0'
    gem 'rspec-rails', '~> 3.1.0'
    gem 'factory_girl_rails', '~> 4.5.0'
    gem 'launchy', '~> 2.4.2'
    gem 'shoulda-matchers'
    gem 'pry-rails', '~> 0.3.2'
    gem 'rspec-collection_matchers', '~> 1.1.2'
    gem 'faker'
    gem 'rspec-activemodel-mocks', '~> 1.0.1'
    gem 'timecop'
    gem 'web-console', '~> 2.0'
    gem 'spring'
end
